html5 and php recommendations
HuubMons/HuMo-genealogy pull request #21
Opened 2023-05-11 18:14 UTC by Barcha17

We are in 2023, the use of html5 is recommended.
PHP end tags are useless and can cause problems (even though I personally never had them) see:https://www.php.net/manual/en/language.basic-syntax.instruction-separation.php

2023-05-11 21:03 UTC, HuubMons commented on admin/include/gedcom_asciihtml.php
All comments went wrong in this file.
It's no longer possible to see which charater is processed.

2023-05-11 21:04 UTC, HuubMons commented
I don't know what to do know.

In the last weeks, I changed a LOT of code (still busy changing more code), and all this code is still tested, and will be added at GitHub.

2023-05-11 21:43 UTC, HuubMons commented on admin/include/cal_date.php
I don't understand why the identation is changed from line 18 to 34.
I do think it's better to understand if identation is used.

2023-05-11 21:49 UTC, HuubMons commented on admin/include/editor_person_select.php
Just my personal opinion:
I find lines 9-11 easier to read then 11-20.

I don't mind changing it.

2023-05-11 21:55 UTC, HuubMons commented on include/db_login.php
Just a remark:
It's no use to change this file. If changes are done it's possible the update script will destroy this file and HuMo-genealogy won't run anymore.
So these changes must also be done in the update script (I didn't checked that script yet)

2023-05-12 07:45 UTC, HuubMons commented on address.php
Sorry, I'm trying to understand the changes in this file.
What is happening at lines 36, 40, 52 and 55? It looks like the line is removed and then added again?

2023-05-12 07:51 UTC, HuubMons commented on admin/include/backup.php
> -	printf(__('%s backup'),'HuMo-genealogy');
The identation is removed. But I think the code is better readible if this identation isn't removed.

2023-05-12 08:54 UTC, HuubMons commented on lijst_namen.php
In the past all script names were dutch. Later they were translated into english.
There are a few scripts like this for backwards compatibility.

2023-05-12 11:39 UTC, HuubMons commented
You just changes CMS_ROOTPATH into __DIR__.
That's not possible, because CMS_ROOTPATH is defined in a plugin for Joomla (outside HuMo-genealogy).

2023-05-12 11:40 UTC, HuubMons requested changes
You just changed CMS_ROOTPATH into DIR.
That's not possible, because CMS_ROOTPATH is defined in a plugin for Joomla (outside HuMo-genealogy).

I will think about removing this contant completely. Because it's only used for a few users...

2023-05-12 13:46 UTC, Barcha17 commented
> You just changed CMS_ROOTPATH into **DIR**. That's not possible, because CMS_ROOTPATH is defined in a plugin for Joomla (outside HuMo-genealogy).

I don't delete CMS_ROOTPATH, it's just for more readable and fast execution for include and require.

"Français isn't valid HTML": it's not html but string and 
utf-8

2023-05-12 14:04 UTC, HuubMons commented
Just for your information:

> > You just changed CMS_ROOTPATH into **DIR**. That's not possible, because CMS_ROOTPATH is defined in a plugin for Joomla (outside HuMo-genealogy).
> 
> I don't delete CMS_ROOTPATH, it's just for more readable and fast execution for include and require.
> 
> "Français isn't valid HTML": it's not html but string and utf-8

I will explain about the CMS_ROOTPATH:

In header.php you see this code:
```
// *** Check if HuMo-genealogy is in a CMS system ***
//	Names:
//		- CMS names used for now are 'Joomla' and 'CMSMS'.
//	Usage:
//		- Code for all CMS: if (CMS_SPECIFIC) {}
//		- Code for one CMS: if (CMS_SPECIFIC == 'Joomla') {}
//		- Code NOT for CMS: if (!CMS_SPECIFIC) {}
if (!defined("CMS_SPECIFIC")) define("CMS_SPECIFIC", false);

// *** When run from CMS, the path to the map (that contains this file) should be given ***
if (!defined("CMS_ROOTPATH")) define("CMS_ROOTPATH", "");
```
As you can see the special variable CMS_ROOTPATH is used in HuMo-genealogy plugins in Joomla and CMSMS. Then HuMo-genealogy will read this variable. Without this variable both Joomla and CMSMS HuMo-genealogy plugins won't work anymore.


About "Français isn't valid HTML": it's not html but string and utf-8
This is the name of the language, this variable will be used as ALT when a language flag is shown.

2023-05-12 14:09 UTC, Barcha17 commented
> 
For information: the corrections of the 110 files were made by my IDE which uses a linter (like any IDE worthy of the name) to format the code according to the recommendations of the php language

"this variable will be used as ALT when a language flag is show and also be shown next to a flag" yes and it's a string.

CMS_ROOTPATH define if you're in jomla cms, this should not influence the path of one file to be included in another.

2023-05-12 19:49 UTC, HuubMons commented on admin/include/gedcom_asciihtml.php
Something went wrong with the comments. The ASCII characters are changed into corrupte characters.

2023-05-12 19:54 UTC, HuubMons commented on README.md
Wow, this is an improvement :-) It's a long time ago this file was updated.
Several files can be founded at Sourceforge.
Manual: https://sourceforge.net/projects/humo-gen/files/HuMo-gen_Manual/
Extensions (ip_files.zip): https://sourceforge.net/projects/humo-gen/files/HuMo-gen_EXTENSIONS/

2023-05-12 20:34 UTC, HuubMons commented on include/db_login.php
I will do an extra check of this file!
This file will be rewritten (especially line 4-7) if an automatic update is done. This is done in admin/update/install_update.php line 388 etc.
This will probably work, but I will test this file before releasing a new version.

2023-05-12 20:53 UTC, HuubMons commented on relations.php
Remark for myself: check $generY

2023-05-12 20:57 UTC, HuubMons commented on header.php
Note to myself:
Lines like:
if (!defined("CMS_ROOTPATH")) define("CMS_ROOTPATH", "");
are no longer in use. CMS options won't work anymore, but probably not used a lot.

2023-05-12 21:11 UTC, HuubMons approved these changes

2023-05-12 21:14 UTC, HuubMons commented
I will probably merge these files into the master branch tomorrow (I don't want to loose changes by merging into the development branch).
If it's done, I need to merge my changes into the changed files. I will do some tests, maybe my changes will be merged using WinMerge (and added into the development branch).

2023-05-12 22:28 UTC, Barcha17 commented on relations.php
What that?

2023-05-12 22:30 UTC, Barcha17 commented on header.php
Where? that is required for joomlalala!
The code needs to be cleaned up first.

2023-05-12 22:32 UTC, Barcha17 commented
Hummm, for me the dev branch needs more testing, I found some bugs (see last push comments for next version)

2023-05-13 06:09 UTC, HuubMons commented on header.php
header.php line 17.
The same system is used in line 19: variable CMS_ROOTPATH_ADMIN.

But: it's won't work anymore, because CMS_ROOTPATH is replaced by __DIR.
It's no big deal, it's best to remove all CMS_ROOTPATH items.

In the most recent versions HuMo-genealogy will work if it's included in Joomla or another CMS.
The old Joomla plugin isn't maintained anymore.

So: I don't mind to remove these lines.

2023-05-13 06:19 UTC, HuubMons commented on relations.php
In the code relation.php line 826 a line is added:
// TODO: @DEVS: $generY is undefined here!

2023-05-13 13:47 UTC, HuubMons commented on styles/fontsize.js
About this file:
It's not in use at this moment. There were Fontsize + and - button in HuMo-genealogy.
At one moment the buttons were removed temporary, and never restored. Maybe it's time to remove this script...

2023-05-13 14:33 UTC, HuubMons commented
I created a new branch: development2 (original from master). So it's possible to merge your files into development2.
Then I can try to merge development and development2 branches.
The master branch won't be changed.

2023-05-13 15:57 UTC, HuubMons commented on admin/theme/css/admin.css
admin.css line 3:
Path to file: /admin/theme/images/background.gif
Some providers go to the server root (not website root) if a path starts with /
This is the reason I never start a file path with: /

2023-05-13 16:05 UTC, HuubMons commented on config/application.php
At this moment mail settings are stored into the database.

Database login settings are stored in: include/db_login.php.
The file db_login.php will be rewritten if an automatic HuMo-genealogy update is done. I made this so it's possible to make changes into the db_login.php file.
After update the database connection is restored.

2023-05-13 16:15 UTC, HuubMons commented
Remark: at this moment I'm using an old version of CK_Editor, because it was the last free version that supports upload of media.
Do you know a good (freeware) alternative for CKEditor?

2023-05-13 17:13 UTC, Barcha17 commented on config/application.php
Just for prepare 7.0 for testing not used actualy.

2023-05-13 17:17 UTC, Barcha17 commented on styles/fontsize.js
I'am agree with you. Removed.

2023-05-13 17:20 UTC, Barcha17 commented on admin/theme/css/admin.css
Yes, you're right, Modified.

2023-05-13 17:22 UTC, Barcha17 commented on relations.php
I don't what this $generY. Not declared as global and not in function attribute. Maybe in an older code?

2023-05-13 17:24 UTC, Barcha17 commented
> 
Topic in discussion.

2023-05-13 17:27 UTC, Barcha17 commented on include/db_login.php
Only formater and inclure/require path, nothing changed.

2023-05-13 17:44 UTC, Barcha17 commented on relations.php
I change the code, need some tests.

2023-05-13 17:50 UTC, Barcha17 commented
Can you create a new branch 7.0-dev? I have to pull request on this new branch not in master branch.

2023-05-13 18:36 UTC, HuubMons commented
> 

I have created the branch. But GitHub copies the master files automatically.

2023-05-13 18:37 UTC, Barcha17 commented
> > 
> 
> I have created the branch. But GitHub copies the master files automatically. So it's not empty at this moment.

Just 7.0-dev not with "branch" please mister.

2023-05-13 18:53 UTC, HuubMons commented
> 7.0-dev

Done!

2023-05-13 19:05 UTC, Barcha17 commented
> > 7.0-dev
> 
> Done!

Ok! We can create the 6.x branch from master and delete development branch's who are useless after.

2023-05-13 19:09 UTC, HuubMons commented
In the last weeks I changed about 60 files. They are added in the branch: development.

2023-05-13 19:26 UTC, Barcha17 commented
> 

You can rename the branch "development" to "6.x".

2023-05-13 20:34 UTC, HuubMons commented
> > 
> 
> You can rename the branch "development" to "6.x". if it's always a 6.1.1.1 structure.

I don't understand... I don't want to lose all my script changes from last weeks.
I have changed quit a lot in the editor and several other files.

2023-05-13 21:36 UTC, Barcha17 commented
> 

Ok, delete the 6.x branch in github and this pull request, create branch 6.x from github master and push your local job branch to the 6.x on github,

2023-05-14 07:08 UTC, closed without merging

2023-05-14 07:08 UTC, HuubMons commented
This pull request is closed. It's allready added in dev-7.0